services:
  db:
    container_name: db
    image: postgres:15.6
    restart: on-failure
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
