// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"apps/reservation-service/internal/application/commands"
	"apps/reservation-service/internal/application/commands/reservation"
	"apps/reservation-service/internal/application/queries"
	"apps/reservation-service/internal/infrastructure/command_bus"
	"apps/reservation-service/internal/infrastructure/query_bus"
	"apps/reservation-service/internal/infrastructure/repository"
)

// Injectors from initialize.go:

func InitializeApp() App {
	commandBus := command_bus.NewCommandBus()
	reservationRepository := repository.ProvideReservationRepository()
	createReservationHandler := command.NewCreateReservationHandler(reservationRepository)
	commandBusSetup := command_setup.NewCommandSetup(commandBus, createReservationHandler)
	queryBus := query_bus.NewQueryBus()
	queryBusSetup := query_setup.NewQuerySetup(queryBus)
	app := NewApp(commandBusSetup, queryBusSetup)
	return app
}

// initialize.go:

type App struct {
	CommandBus *command_bus.CommandBus
	QueryBus   *query_bus.QueryBus
}

func NewApp(cmdSetup command_setup.CommandBusSetup, querySetup query_setup.QueryBusSetup) App {
	return App{
		CommandBus: cmdSetup.Bus,
		QueryBus:   querySetup.Bus,
	}
}
