import { DayOfWeek, Restaurant } from '@generated/graphql';

export const mockRestaurants: Restaurant[] = [
  {
    __typename: 'Restaurant',
    id: '1',
    name: 'The Gourmet Spot',
    address: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cuisineType: 'Italian',
    email: 'contact@gourmetspot.com',
    isActive: true,
    operatingHours: [
      { dayOfWeek: DayOfWeek.Monday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Tuesday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Wednesday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Thursday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Friday, openTime: '10:00 AM', closeTime: '11:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Saturday, openTime: '11:00 AM', closeTime: '11:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Sunday, openTime: '11:00 AM', closeTime: '9:00 PM', isClosed: false },
    ],
    phoneNumber: '+1-555-1234',
    photos: ['https://example.com/photos/gourmetspot1.jpg', 'https://example.com/photos/gourmetspot2.jpg'],
    rating: 4.5,
    website: 'https://gourmetspot.com',
  },
  {
    __typename: 'Restaurant',
    id: '2',
    name: 'Sushi Paradise',
    address: {
      street: '456 Ocean Ave',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90012',
      country: 'USA',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cuisineType: 'Japanese',
    email: 'info@sushiparadise.com',
    isActive: true,
    operatingHours: [
      { dayOfWeek: DayOfWeek.Monday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Tuesday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Wednesday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Thursday, openTime: '10:00 AM', closeTime: '10:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Friday, openTime: '10:00 AM', closeTime: '11:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Saturday, openTime: '11:00 AM', closeTime: '11:00 PM', isClosed: false },
      { dayOfWeek: DayOfWeek.Sunday, openTime: '11:00 AM', closeTime: '9:00 PM', isClosed: false },
    ],
    phoneNumber: '+1-555-5678',
    photos: ['https://example.com/photos/sushiparadise1.jpg', 'https://example.com/photos/sushiparadise2.jpg'],
    rating: 4.8,
    website: 'https://sushiparadise.com',
  },
];
